config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :posts do
    resources :likes, only: %i[index create destroy]
  end
  resources :friend_requests, only: %i[index update create]
  resources :profile, only: %i[show edit update]
  resources :comments, only: %i[create] do 
    resources :likes, only: %i[index create destroy]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender_friend, class_name: "User"
  belongs_to :reciever_friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, as: :likeable, dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy

  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :sended_friend_requests,
           foreign_key: :sender_friend_id,
           class_name: 'FriendRequest',
           dependent: :destroy

  has_many :recieved_friend_requests, 
           foreign_key: :reciever_friend_id,
           class_name: 'FriendRequest',
           dependent: :destroy

  has_many :posts, dependent: :destroy

  has_one :profile, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :comments, dependent: :destroy

  after_create :init_profile

  def pending_friend_requests
    recieved_friend_requests.where(state: 'pending')
  end

  def friends_ids
    sended_requests = FriendRequest.where("sender_friend_id = ? and state = 'accepted'", id)
                                   .pluck(:reciever_friend_id)
    recieved_requests = FriendRequest.where("reciever_friend_id = ? and state = 'accepted'", id)
                                     .pluck(:sender_friend_id)
    [sended_requests, recieved_requests].flatten
  end

  def other_users
    ids = []
    ids << id
    ids << friends_ids
    ids << sended_friend_requests.where("state = 'pending'").pluck(:reciever_friend_id)
    ids << recieved_friend_requests.where("state = 'pending'").pluck(:sender_friend_id)
    User.where.not(id: ids.flatten).includes(:profile)
  end

  def init_profile
    build_profile.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @commentable = Post.find(params[:commentable_id]) if params[:commentable_type] == 'Post'
    @commentable = Comment.find(params[:commentable_id]) if params[:commentable_type] == 'Comment'
    @commentable.comments.create({ user_id: current_user.id, body: params[:body] })
    redirect_to posts_path
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @friend_requests = current_user.pending_friend_requests.all
  end

  def create
    @request = current_user.sended_friend_requests.create!(friend_request_params)
    redirect_to posts_path
  end

  def update
    @friend_request = FriendRequest.find(params[:id])
    @friend_request.update(friend_request_params)
    redirect_to friend_requests_path
  end

  private

  def friend_request_params
    params.require(:friend_request).permit(:state, :reciever_friend_id)
  end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Post.find(params[:post_id]).likes if params[:post_id]
    @likes = Comment.find(params[:comment_id]).likes if params[:comment_id]
  end

  def create
    @likeable = Post.find(params[:post_id]) if params[:post_id]
    @likeable = Comment.find(params[:comment_id]) if params[:comment_id]
    unless @likeable.likes.where('user_id = ?', current_user.id).exists?
      @likeable.likes.create({ user_id: current_user.id })
    end
    redirect_to posts_path
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = current_user.posts.build

    @user_liked_posts_ids = current_user.likes.where("likeable_type = 'Post'").pluck(:likeable_id)
    @posts = Post.all.includes(:likes, :comments, user: [:profile])

    @friends = User.where(id: current_user.friends_ids).includes(:profile)
  end

  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path, notice: "Your post has been created"
    else 
      render :new
    end 
    
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to @profile
    else
      flash.now[alert] = "Couldn't edit profile"
      render :edit
    end
  end

  def profile_params
    params.require(:profile).permit(:birthday, :country, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_requests/index.html.erb
<% @friend_requests.each do |fr| %>
  <div class="card">
    <div class="card-body">
      <p><%= fr.sender_friend.email %> wants to be your friend!</p>
      <div class="d-flex">
        <%= form_with model: fr, method: "patch" do |f| %>
          <%= f.hidden_field :state, value: "accepted" %>
          <%= f.submit "Accept", class: "btn btn-primary mx-1" %>
        <% end %>
        <%= form_with model: fr, method: "patch" do |f| %>
          <%= f.hidden_field :state, value: "declined" %>
          <%= f.submit "Decline", class: "btn btn-primary mx-1" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
  <div class="container-fluid">
    
    <% if user_signed_in? %>
      <div>
        <%= link_to "Fakebook", root_path, class: "navbar-brand h1" %>
        <span class= "navbar-text">Hello <%= current_user.name %></span>
      </div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", profile_path(current_user.profile), class: "nav-link active" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notifications 
            <% if current_user.pending_friend_requests.any? %>
              <sup><strong><%= current_user.pending_friend_requests.length %></strong></sup>
            <% end %>
          </a>
          <ul class="dropdown-menu px-4" aria-labelledby="navbarDropdownMenuLink">
            <% current_user.pending_friend_requests.each do |request| %>
            <li>
              <strong><%=request.sender_friend.name %></strong> has send you an
              <%= link_to "invitation", friend_requests_path %>
            </li>
            <% end %>
          </ul>
        </li>
        
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link active" %>
        </li>
        
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </head>

  <body style="background-color: #edf0f3">
    <%= render "layouts/navbar" %>
    <% flash.each do |type, msg| %>
      <% if type == "alert" %>
        <div class="alert alert-warning alert-dismissible fade show">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% else %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>
    <div class="container-fluid"> 
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/likes/index.html.erb
<ul class="list-group">
  <% @likes.each do |like| %>
    <li class="list-group-item">
      <%= link_to like.user.name, profile_path(like.user.profile) %>
    </li>
  <% end %>
</ul>

app/views/posts/_card.erb
<div class="card mt-4">
  <div class="card-header py-1 d-flex justify-content-between">
    <h5 class="card-title"><%= post.user.email%></h5>
    <div class="header-buttons">
      <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-primary" %>
      <%= link_to "Delete", post_path(post), method: "delete", class: "btn btn-outline-primary" %>
    </div>
  </div>
  <div class="card-body mt-0">
    <p class="card-text"><%= post.body %></p>
  </div>
  <div class="card-footer">
    <button class="btn btn-primary mt-2">Like</button>
    <button class="btn btn-secondary mt-2">Comment</button>
  </div>
</div>

app/views/posts/_comment.html.erb
<div class="rounded p-2" style="background-color: #ddebff">
  <p><strong><%= comment.user.name %></strong></p>
  <p><%= comment.body %></p>
</div>
<% unless comment.likes.where("user_id = #{current_user.id}").exists? %>
  <%= link_to 'Like',
    comment_likes_path(comment),
    method: 'post',
    class: 'btn btn-outline-secondary' 
  %>
<% else %>
  <% like = comment.likes.where("user_id = #{current_user.id}").first%>
  <%= link_to 'Unlike',
    comment_like_path(comment, like.id),
    method: 'delete',
    class: 'btn btn-outline-primary' 
  %>
<% end %>
<% if comment.likes.any? %>
  <%= link_to "#{comment.likes.length} likes", comment_likes_path(comment), class: 'btn btn-primary btn-sm rounded-circle' %>
<% end %>
<div class="row mt-2">
  <%= render partial: 'new_comment', locals: {commentable_id: comment.id, commentable_type: "Comment"} %>
  <div class="col-12 mt-2 pl-5">
    <%= render partial: 'comment', collection: comment.comments %>
  </div>
</div>

app/views/posts/_form.erb
<div class="card mt-4">
  <div class="card-body text-center">
    <h5 class="card-title"><%= title %></h5>
    <%= form_with model: post, method: method do |form| %>
      <%= form.text_area :body, class: "card-text form-control" %>
      <%= form.submit "Publish", class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="card mt-4">
  <div class="card-body text-center">
    <h5 class="card-title"><%= title %></h5>
    <%= form_with model: post, method: method do |form| %>
      <%= form.text_area :body, class: "card-text form-control" %>
      <%= form.submit "Publish", class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
</div>

app/views/posts/_new_comment.html.erb
<%= form_with url: comments_path, method: 'post', class: "col-12 d-flex my-2" do |form| %>
  <%= form.hidden_field :commentable_id, value: commentable_id %>
  <%= form.hidden_field :commentable_type, value: commentable_type %>
  <%= form.text_field :body, class: 'form-control' %>
  <%= form.submit 'Comment', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_new_post.html.erb
<div class="card mt-4">
  <div class="card-body text-center">
    <h5 class="card-title">Create Post</h5>
    <%= form_with model: @post do |form| %>
      <%= form.text_area :body, class: "card-text form-control" %>
      <%= form.submit "Publish", class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="card mt-4">
  <div class="card-header py-1 d-flex justify-content-between">
    <div></div>
    <h5 class="card-title">
      <img src=<%= post.user.profile.photo %> width="30px" height="30px">
      <%= link_to post.user.name, post.user.profile %>
    </h5>
    <% if post.user == current_user%>
      <div class="header-buttons">
        <%= link_to edit_post_path(post) do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to post_path(post), method: "delete" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    <% else %>
      <div></div>
    <% end %>
  </div>
  <div class="card-body mt-0">
    <p class="card-text"><%= post.body %></p>
  </div>
  <div class="card-footer container">
    <div class="row">
      <div class="col-12">
        <% unless @user_liked_posts_ids.include?(post.id) %>
          <%= link_to 'Like',
            post_likes_path(post),
            method: 'post',
            class: 'btn btn-outline-secondary ' 
          %>
        <% else %>
          <% like = post.likes.find_by(user_id: current_user.id) %>
          <%= link_to 'Like',
            post_like_path(post, like.id),
            method: 'delete',
            class: 'btn btn-outline-primary' 
          %>
        <% end %>
        
        <% if post.likes.any? %>
          <%= link_to post_likes_path(post) do %>
            <span class="btn btn-primary btn-sm rounded-circle">
              <i class="far fa-thumbs-up"></i>
            </span>
            <%= post.likes.length %> 
          <% end%>
        <% end %>
      </div>
    </div>
    <div class="row mt-2">
      <%= render partial: 'new_comment', locals: {commentable_id: post.id, commentable_type: "Post"} %>
      <h5 class="col-12 mt-2">Comments</h5>
      <div class="col-12 mt-2">
        <%= render partial: 'comment', collection: post.comments %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class="card mt-4">
  <div class="card-body text-center">
    <h5 class="card-title"><%= title %></h5>
    <%= form_with model: post, method: method do |form| %>
      <%= form.text_area :body, class: "card-text form-control" %>
      <%= form.submit "Publish", class: "btn btn-primary mt-2" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "form", locals: { post: @post, title: "Edit post", method: "patch" }%>

app/views/posts/index.html.erb
<div class="row justify-content-between"> 
  <div class="col-lg-3">
    <div class="card mt-4">
      <div class="card-header py-1 d-flex justify-content-between">
        <h5 class="card-title">Friends</h5>
      </div>
      <div class="card-body mt-0">
        <ul class="list-group">
          <% @friends.each do |friend| %>
            <li class="list-group-item">
              <img src=<%= friend.profile.photo %> width="30px" height="30px" style="border-radius: 50%">
              <%= link_to friend.name, friend.profile %>
            </li>
          <% end %>
        </ul>
      </div>
    </div></div>
  <div class="col-lg-6">
    <%= render partial: "post_form", locals: { post: @post, title: "Create Post", method: "post" } %>
    <%= render @posts %>
  </div>
  <div class="col-lg-3">
    <div class="card mt-4">
      <div class="card-header py-1 d-flex justify-content-between">
        <h5 class="card-title">Other users</h5>
      </div>
      <div class="card-body mt-0">
        <ul class="list-group overflow-auto" style="height: 600px">
          <% current_user.other_users.each do |user| %>
            <li class="d-flex list-group-item justify-content-between">
              <img src=<%= user.profile.photo %> width="30px" height="30px" style="border-radius: 50%">
              <%= link_to user.name, user.profile, class: 'text-center' %>
              <%= form_with model: current_user.sended_friend_requests.build do |form| %>
                <%= form.hidden_field :reciever_friend_id, value: user.id %>
                <%= form.hidden_field :state, value: "pending" %>
                <%= form.submit "Add", class: "btn btn-primary btn-sm ml-2" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  
</div>

app/views/posts/new.html.erb
<%= render partial: "form", locals: { post: @post, title: "Create Post", method: "post" }%>